security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        entity_provider:
            entity:
                class: App\Entity\User
                property: accountId
    firewalls:
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        register:
            pattern:  ^/register
            stateless: true
            anonymous: true
        api:
            pattern:   ^/api/customer
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        logout:
            pattern:   ^/logout
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        api_bank:
            pattern:   ^/api/bank
            stateless: true
            anonymous: true

    access_control:
        - { path: ^/login_check,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,       roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/customer,   roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/logout,         roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/bank,       roles: IS_AUTHENTICATED_ANONYMOUSLY }